### ISSUE TITLE
ProgressTrack: enforce upper/lower bound when using advancement methods

### ISSUE THREAD

**Issue by zkat** [cwegrzyn/obsidian-forged#64]
You can make even bounded ProgressTracks go negative, or overflow past 40. We should make the `advanced` methods take this into account and clamp the result appropriately.

**Comment by cwegrzyn** [comment]
Oh, hmm, you are definitely right on the negative bound. But what's a scenario where you can get a bounded track to go over 40? That control is there and I thought tested.

**Comment by zkat** [comment]
isn't the whole point of a bounded track that you stop at 40? Unbounded ones are the ones that can overflow, right?

**Comment by zkat** [comment]
oh sorry, I misread.

It was happening before. I can't repro it anymore. So I guess we only need to watch out for negatives now. :)
